# Generated by Django 5.1.2 on 2024-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smk_parse', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embeddings',
            field=models.BinaryField(null=True),
        ),
    ]
