# Generated by Django 5.1.2 on 2024-12-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smk_parse', '0003_product_embeddings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='embeddings',
            new_name='embedding',
        ),
    ]
